/**
 * OrderStack REST API client.
 *
 * This file is auto-generated by the codegen.yml GitHub Actions workflow
 * after each deployment to staging. Do not edit manually.
 *
 * To regenerate:
 *   npx openapi-typescript https://api-staging.orderstack.io/docs/json \
 *     --output packages/api-client/src/schema.ts
 */

export { createApiClient } from './client.js'
export type { ApiClientConfig } from './client.js'
